#pragma once

// #include "dudis2d/core/debug/dd-debug.h"
#include "dudis2d/core/log/log.h"
// #include "dudis2d/core/model/model.h"
#include "dudis2d/core/motion/easing/easing.h"
#include "dudis2d/core/utils/types.h"
#include "dudis2d/core/utils/utils.h"
#include "dudis2d/platform/window/window.h"
#include "dudis2d/globals/app.h"
#include "dudis2d/scenes/scene/scene.h"
#include "dudis2d/scenes/sceneManager/sceneManager.h"
#include "dudis2d/scenes/sceneProperty/sceneProperty.h"
#include "dudis2d/platform/input/input.h"
#include "dudis2d/platform/input/keyboard.h"
#include "dudis2d/platform/input/mouse.h"
#include "dudis2d/globals/time.h"
