#include "dudis2d/platform/ddrlUtils/toRLKey.h"
#include "raylib.h"

namespace dudis
{
    namespace ddrlUtils
    {
        using Key = KeyCode;
        int toRaylibKey(KeyCode k)
        {
            switch (k)
            {
            case KeyCode::Unknown:
                return KEY_NULL;
            case Key::A:
                return KEY_A;
            case Key::B:
                return KEY_B;
            case Key::C:
                return KEY_C;
            case Key::D:
                return KEY_D;
            case Key::E:
                return KEY_E;
            case Key::F:
                return KEY_F;
            case Key::G:
                return KEY_G;
            case Key::H:
                return KEY_H;
            case Key::I:
                return KEY_I;
            case Key::J:
                return KEY_J;
            case Key::K:
                return KEY_K;
            case Key::L:
                return KEY_L;
            case Key::M:
                return KEY_M;
            case Key::N:
                return KEY_N;
            case Key::O:
                return KEY_O;
            case Key::P:
                return KEY_P;
            case Key::Q:
                return KEY_Q;
            case Key::R:
                return KEY_R;
            case Key::S:
                return KEY_S;
            case Key::T:
                return KEY_T;
            case Key::U:
                return KEY_U;
            case Key::V:
                return KEY_V;
            case Key::W:
                return KEY_W;
            case Key::X:
                return KEY_X;
            case Key::Y:
                return KEY_Y;
            case Key::Z:
                return KEY_Z;

            case Key::Num0:
                return KEY_ZERO;
            case Key::Num1:
                return KEY_ONE;
            case Key::Num2:
                return KEY_TWO;
            case Key::Num3:
                return KEY_THREE;
            case Key::Num4:
                return KEY_FOUR;
            case Key::Num5:
                return KEY_FIVE;
            case Key::Num6:
                return KEY_SIX;
            case Key::Num7:
                return KEY_SEVEN;
            case Key::Num8:
                return KEY_EIGHT;
            case Key::Num9:
                return KEY_NINE;

            case Key::Escape:
                return KEY_ESCAPE;
            case Key::Space:
                return KEY_SPACE;
            case Key::Enter:
                return KEY_ENTER;
            case Key::Tab:
                return KEY_TAB;
            case Key::Backspace:
                return KEY_BACKSPACE;
            case Key::Insert:
                return KEY_INSERT;
            case Key::Delete:
                return KEY_DELETE;
            case Key::Home:
                return KEY_HOME;
            case Key::End:
                return KEY_END;
            case Key::PageUp:
                return KEY_PAGE_UP;
            case Key::PageDown:
                return KEY_PAGE_DOWN;

            case Key::Left:
                return KEY_LEFT;
            case Key::Right:
                return KEY_RIGHT;
            case Key::Up:
                return KEY_UP;
            case Key::Down:
                return KEY_DOWN;

            case Key::CapsLock:
                return KEY_CAPS_LOCK;
            case Key::ScrollLock:
                return KEY_SCROLL_LOCK;
            case Key::NumLock:
                return KEY_NUM_LOCK;
            case Key::PrintScreen:
                return KEY_PRINT_SCREEN;
            case Key::Pause:
                return KEY_PAUSE;

            case Key::LeftShift:
                return KEY_LEFT_SHIFT;
            case Key::RightShift:
                return KEY_RIGHT_SHIFT;
            case Key::LeftControl:
                return KEY_LEFT_CONTROL;
            case Key::RightControl:
                return KEY_RIGHT_CONTROL;
            case Key::LeftAlt:
                return KEY_LEFT_ALT;
            case Key::RightAlt:
                return KEY_RIGHT_ALT;
            case Key::LeftSuper:
                return KEY_LEFT_SUPER;
            case Key::RightSuper:
                return KEY_RIGHT_SUPER;
            case Key::Menu:
                return KEY_KB_MENU;

            case Key::F1:
                return KEY_F1;
            case Key::F2:
                return KEY_F2;
            case Key::F3:
                return KEY_F3;
            case Key::F4:
                return KEY_F4;
            case Key::F5:
                return KEY_F5;
            case Key::F6:
                return KEY_F6;
            case Key::F7:
                return KEY_F7;
            case Key::F8:
                return KEY_F8;
            case Key::F9:
                return KEY_F9;
            case Key::F10:
                return KEY_F10;
            case Key::F11:
                return KEY_F11;
            case Key::F12:
                return KEY_F12;
            case Key::F13:
            case Key::F14:
            case Key::F15:
            case Key::F16:
            case Key::F17:
            case Key::F18:
            case Key::F19:
            case Key::F20:
            case Key::F21:
            case Key::F22:
            case Key::F23:
            case Key::F24:
                return KEY_NULL;

            case Key::Minus:
                return KEY_MINUS;
            case Key::Equal:
                return KEY_EQUAL;
            case Key::LeftBracket:
                return KEY_LEFT_BRACKET;
            case Key::RightBracket:
                return KEY_RIGHT_BRACKET;
            case Key::Backslash:
                return KEY_BACKSLASH;
            case Key::Semicolon:
                return KEY_SEMICOLON;
            case Key::Apostrophe:
                return KEY_APOSTROPHE;
            case Key::Grave:
                return KEY_GRAVE;
            case Key::Comma:
                return KEY_COMMA;
            case Key::Period:
                return KEY_PERIOD;
            case Key::Slash:
                return KEY_SLASH;

            case Key::Numpad0:
                return KEY_KP_0;
            case Key::Numpad1:
                return KEY_KP_1;
            case Key::Numpad2:
                return KEY_KP_2;
            case Key::Numpad3:
                return KEY_KP_3;
            case Key::Numpad4:
                return KEY_KP_4;
            case Key::Numpad5:
                return KEY_KP_5;
            case Key::Numpad6:
                return KEY_KP_6;
            case Key::Numpad7:
                return KEY_KP_7;
            case Key::Numpad8:
                return KEY_KP_8;
            case Key::Numpad9:
                return KEY_KP_9;
            case Key::NumpadDecimal:
                return KEY_KP_DECIMAL;
            case Key::NumpadDivide:
                return KEY_KP_DIVIDE;
            case Key::NumpadMultiply:
                return KEY_KP_MULTIPLY;
            case Key::NumpadSubtract:
                return KEY_KP_SUBTRACT;
            case Key::NumpadAdd:
                return KEY_KP_ADD;
            case Key::NumpadEnter:
                return KEY_KP_ENTER;
            case Key::NumpadEqual:
                return KEY_KP_EQUAL;

            case Key::VolumeMute:
                return KEY_NULL;
            case Key::VolumeDown:
                return KEY_VOLUME_DOWN;
            case Key::VolumeUp:
                return KEY_VOLUME_UP;
            case Key::MediaPlayPause:
            case Key::MediaStop:
            case Key::MediaNext:
            case Key::MediaPrev:
                return KEY_NULL;
            }

            return KEY_NULL;
        }

    }
}
