name: Linux GCC Build

on:
  push:
  pull_request:

jobs:
  build-and-test-unit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          libx11-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libxi-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev

    - name: Configure unit tests
      working-directory: dudis-2d/tests
      run: cmake --preset tests-debug

    - name: Build unit test preset
      working-directory: dudis-2d/tests
      run: cmake --build build/unit-debug

    - name: Run unit tests
      working-directory: dudis-2d/tests
      run: ctest --test-dir build/unit-debug -L unit --output-on-failure
